package com.doocker.crm.po;

import java.util.Date;

public class Seekfollow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seekfollow.followid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Integer followid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seekfollow.seekDate
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Date seekdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seekfollow.stuname
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String stuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seekfollow.seekFun
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String seekfun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seekfollow.seekby
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String seekby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seekfollow.seekRus
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String seekrus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seekfollow.followid
     *
     * @return the value of seekfollow.followid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Integer getFollowid() {
        return followid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seekfollow.followid
     *
     * @param followid the value for seekfollow.followid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setFollowid(Integer followid) {
        this.followid = followid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seekfollow.seekDate
     *
     * @return the value of seekfollow.seekDate
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Date getSeekdate() {
        return seekdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seekfollow.seekDate
     *
     * @param seekdate the value for seekfollow.seekDate
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setSeekdate(Date seekdate) {
        this.seekdate = seekdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seekfollow.stuname
     *
     * @return the value of seekfollow.stuname
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seekfollow.stuname
     *
     * @param stuname the value for seekfollow.stuname
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seekfollow.seekFun
     *
     * @return the value of seekfollow.seekFun
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getSeekfun() {
        return seekfun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seekfollow.seekFun
     *
     * @param seekfun the value for seekfollow.seekFun
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setSeekfun(String seekfun) {
        this.seekfun = seekfun == null ? null : seekfun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seekfollow.seekby
     *
     * @return the value of seekfollow.seekby
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getSeekby() {
        return seekby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seekfollow.seekby
     *
     * @param seekby the value for seekfollow.seekby
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setSeekby(String seekby) {
        this.seekby = seekby == null ? null : seekby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seekfollow.seekRus
     *
     * @return the value of seekfollow.seekRus
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getSeekrus() {
        return seekrus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seekfollow.seekRus
     *
     * @param seekrus the value for seekfollow.seekRus
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setSeekrus(String seekrus) {
        this.seekrus = seekrus == null ? null : seekrus.trim();
    }
}