package com.doocker.crm.po;

public class Studentseek {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentseek.seekid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Integer seekid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentseek.stuname
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String stuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentseek.stusex
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Integer stusex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentseek.stuphone
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Long stuphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentseek.stuqq
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Integer stuqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentseek.stuclass
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String stuclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentseek.stustatus
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String stustatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentseek.staffid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String staffid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentseek.seekid
     *
     * @return the value of studentseek.seekid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Integer getSeekid() {
        return seekid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentseek.seekid
     *
     * @param seekid the value for studentseek.seekid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setSeekid(Integer seekid) {
        this.seekid = seekid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentseek.stuname
     *
     * @return the value of studentseek.stuname
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentseek.stuname
     *
     * @param stuname the value for studentseek.stuname
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentseek.stusex
     *
     * @return the value of studentseek.stusex
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Integer getStusex() {
        return stusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentseek.stusex
     *
     * @param stusex the value for studentseek.stusex
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStusex(Integer stusex) {
        this.stusex = stusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentseek.stuphone
     *
     * @return the value of studentseek.stuphone
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Long getStuphone() {
        return stuphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentseek.stuphone
     *
     * @param stuphone the value for studentseek.stuphone
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStuphone(Long stuphone) {
        this.stuphone = stuphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentseek.stuqq
     *
     * @return the value of studentseek.stuqq
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Integer getStuqq() {
        return stuqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentseek.stuqq
     *
     * @param stuqq the value for studentseek.stuqq
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStuqq(Integer stuqq) {
        this.stuqq = stuqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentseek.stuclass
     *
     * @return the value of studentseek.stuclass
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getStuclass() {
        return stuclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentseek.stuclass
     *
     * @param stuclass the value for studentseek.stuclass
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStuclass(String stuclass) {
        this.stuclass = stuclass == null ? null : stuclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentseek.stustatus
     *
     * @return the value of studentseek.stustatus
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getStustatus() {
        return stustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentseek.stustatus
     *
     * @param stustatus the value for studentseek.stustatus
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStustatus(String stustatus) {
        this.stustatus = stustatus == null ? null : stustatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentseek.staffid
     *
     * @return the value of studentseek.staffid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentseek.staffid
     *
     * @param staffid the value for studentseek.staffid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStaffid(String staffid) {
        this.staffid = staffid == null ? null : staffid.trim();
    }
}