package com.doocker.crm.po;

import java.util.Date;

public class Transfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.tid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.tdate
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Date tdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.staff_id_bef
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String staffIdBef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.staff_id_now
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String staffIdNow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.byno
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private Integer byno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer.byreason
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    private String byreason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.tid
     *
     * @return the value of transfer.tid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.tid
     *
     * @param tid the value for transfer.tid
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.tdate
     *
     * @return the value of transfer.tdate
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Date getTdate() {
        return tdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.tdate
     *
     * @param tdate the value for transfer.tdate
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setTdate(Date tdate) {
        this.tdate = tdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.staff_id_bef
     *
     * @return the value of transfer.staff_id_bef
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getStaffIdBef() {
        return staffIdBef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.staff_id_bef
     *
     * @param staffIdBef the value for transfer.staff_id_bef
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStaffIdBef(String staffIdBef) {
        this.staffIdBef = staffIdBef == null ? null : staffIdBef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.staff_id_now
     *
     * @return the value of transfer.staff_id_now
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getStaffIdNow() {
        return staffIdNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.staff_id_now
     *
     * @param staffIdNow the value for transfer.staff_id_now
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setStaffIdNow(String staffIdNow) {
        this.staffIdNow = staffIdNow == null ? null : staffIdNow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.byno
     *
     * @return the value of transfer.byno
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public Integer getByno() {
        return byno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.byno
     *
     * @param byno the value for transfer.byno
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setByno(Integer byno) {
        this.byno = byno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer.byreason
     *
     * @return the value of transfer.byreason
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public String getByreason() {
        return byreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer.byreason
     *
     * @param byreason the value for transfer.byreason
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    public void setByreason(String byreason) {
        this.byreason = byreason == null ? null : byreason.trim();
    }
}