package com.doocker.crm.mapper;

import com.doocker.crm.po.Seekfollow;
import com.doocker.crm.po.SeekfollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeekfollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int countByExample(SeekfollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int deleteByExample(SeekfollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int deleteByPrimaryKey(Integer followid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int insert(Seekfollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int insertSelective(Seekfollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    List<Seekfollow> selectByExample(SeekfollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    Seekfollow selectByPrimaryKey(Integer followid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Seekfollow record, @Param("example") SeekfollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int updateByExample(@Param("record") Seekfollow record, @Param("example") SeekfollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int updateByPrimaryKeySelective(Seekfollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seekfollow
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int updateByPrimaryKey(Seekfollow record);
}