package com.doocker.crm.mapper;

import com.doocker.crm.po.Studentseek;
import com.doocker.crm.po.StudentseekExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentseekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int countByExample(StudentseekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int deleteByExample(StudentseekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int deleteByPrimaryKey(Integer seekid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int insert(Studentseek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int insertSelective(Studentseek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    List<Studentseek> selectByExample(StudentseekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    Studentseek selectByPrimaryKey(Integer seekid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Studentseek record, @Param("example") StudentseekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int updateByExample(@Param("record") Studentseek record, @Param("example") StudentseekExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int updateByPrimaryKeySelective(Studentseek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentseek
     *
     * @mbggenerated Tue Jul 25 15:27:57 CST 2017
     */
    int updateByPrimaryKey(Studentseek record);
    List<HashMap> seekSelect (@Param("stuname") String stuname);
}